name: Amazon Linux Docker

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: ["clang", "gcc10"]
        PORTABLE: ["0", "1"]
        CONTAINER: ["amazonlinux:2", "amazonlinux:latest"]
      fail-fast: false
    container: ${{ matrix.CONTAINER }}
    steps:

    - name: Install Amazon Linux pre-deps
      run: yum install -y sudo tar gzip git > /dev/null 2>&1;

    - uses: actions/checkout@v3

    - name: Install Amazon Linux deps
      run: ./misc/install-amazonlinux-deps.sh

    - name: Gather compiler info
      run: gcc -v && clang -v

    - name: Build
      run: CC=${{ matrix.CC }} CFLAGS="-fno-lto" HIGHCTIDH_PORTABLE=${{ matrix.PORTABLE }} make
    - name: Test install
      run: CC=${{ matrix.CC }} HIGHCTIDH_PORTABLE=${{ matrix.PORTABLE }} make install

    - name: Register libraries
      run: sudo ldconfig /usr/local/lib

    - name: Build examples
      run: CC=${{ matrix.CC }} HIGHCTIDH_PORTABLE=${{ matrix.PORTABLE }} make examples

    - name: Run examples
      run: CC=${{ matrix.CC }} HIGHCTIDH_PORTABLE=${{ matrix.PORTABLE }} make examples-run

    - name: Examine build artifacts
      run: ls -alh dist/*.so && sha256sum dist/*.so
