name: Windows Msys2 64bit (ucrt,msvcrt) clang Python pip build and test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        OS: ["windows-2022"]
        CC: ["clang"]
        ENVIRONMENT: ["CLANG64", "MINGW64"] # https://www.msys2.org/docs/environments/
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.ENVIRONMENT }}
        install: >-
          python
          python-pip
          python-build
          python-setuptools
          python-wheel
          python-pytest
          git
          clang
          mingw-w64-clang-x86_64-python-pytest-xdist
          mingw-w64-clang-x86_64-python-flit
          mingw-w64-clang-x86_64-python-distutils-extra
          mingw-w64-x86_64-clang
          make

    - name: Gather runtime environment
      shell: msys2 {0}
      run: |
       uname -a
       python -V
       bash --version
       ${{ matrix.CC }} -v

#   - name: Install dependencies
#     shell: msys2 {0}
#     run: python -m pip install --upgrade flit

    - name: Build highctidh
      shell: msys2 {0}
      run: |
        export SETUPTOOLS_USE_DISTUTILS=local
        export SOURCE_DATE_EPOCH=`git log -1 --pretty=%ct`
        cd src/ && CC=${{ matrix.CC }} OPT="" python3 setup.py install

    - name: Test with pytest
      shell: msys2 {0}
      run: |
        python -c 'from highctidh import bench; bench.simple_bench()'
        pytest -v
