name: Windows Msys2 64bit (cygwin,msvcrt,ucrt) gcc Python pip build and test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        OS: ["windows-2022"]
        CC: ["gcc"]
        ENVIRONMENT: ["MSYS", "UCRT64", "MINGW64"] # https://www.msys2.org/docs/environments/
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.ENVIRONMENT }}
        install: >-
          python
          python-pip
          python-build
          python-setuptools
          python-wheel
          python-pytest
          git
          gcc
          mingw-w64-clang-x86_64-python-pytest-xdist
          mingw-w64-clang-x86_64-python-flit
          mingw-w64-clang-x86_64-python-distutils-extra
          mingw-w64-x86_64-gcc
          mingw-w64-ucrt-x86_64-gcc
          make

    - name: Gather runtime environment
      shell: msys2 {0}
      run: |
       echo ${{ matrix.ENVIRONMENT }}
       uname -a
       python -V
       bash --version
       ${{ matrix.CC }} -v

    - name: Build highctidh
      shell: msys2 {0}
      run: |
        export SETUPTOOLS_USE_DISTUTILS=local
        export SOURCE_DATE_EPOCH=`git log -1 --pretty=%ct`
        export HIGHCTIDH_PORTABLE=1
        export WINDOWS=1
        export MAKE=make
        CC=${{ matrix.CC }} OPT="" pip install -v -e src/
        #CC=${{ matrix.CC }} OPT="" py -m pip install --global-option build_ext --global-option --compiler=mingw32 -e src/  

    - name: Test with pytest
      shell: msys2 {0}
      run: |
        python -c 'from highctidh import bench; bench.simple_bench()'
        pytest -v
